version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: contraseña-secreta
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
